### ISSUE TITLE
Error send mail

### ISSUE THREAD

**Issue by Michelbe30111** [mobizt/ESP-Mail-Client#305] opened 2023-10-18 06:10 UTC
**Build tool used:**

- [ x] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [ x] ESP8266-based
- [x ] ESP32-based

**Other Libraries That are used:**

**Description of problem:**
example Send_Reuse_Session_mail.ino 
time ok with esp8266
time error with esp32

send mail ok on esp8266
send mail ok for first send  with esp32  and for next send error:
Error, Status Code: 0, Error Code: -2, Reason: data sending failed
Error, Status Code: 0, Error Code: -100, Reason: unable to connect to server
Connection error, Status Code: 0, Error Code: -401, Reason: response read timed out

**Share code snippet to reproduce the issue:**
```cpp
//base32.ino
#include "ini.h"

#ifdef ESP32
#define nom "base32"
#include <WiFi.h>
#elif defined(ESP8266)
#define nom "base8266"
#include <ESP8266WiFi.h>
#endif

bool WifiEtat = true;
#include <FS.h>

#include <ArduinoOTA.h>
#include <LittleFS.h>
#include <FTPServer.h>
FTPServer ftpSrv(LittleFS);

#include <ESP_Mail_Client.h>
SMTPSession smtp;
Session_Config config;
void smtpCallback(SMTP_Status status);
#include "HeapStat.h"
HeapStat heapInfo;

unsigned long sentMillis = 0, tpsmillis = 0;

#include <time.h>
time_t maintenant;
struct tm* timeinfo;
int jour, jouractu;
int heure, heureactu;
char DateHeure[20];

void setup() {
  startserial();
  startWifi();
  if (WifiEtat) {
    //startMDNS();
    startOTA();  
    ftpSrv.begin("esp8266", "esp8266");

    startLittleFS();
    startmail();
    delay(30000);
  }
  EnreEvenement("Fin demarage programme");
}

void loop() {
  ArduinoOTA.handle();
  ftpSrv.handleFTP();
  if (millis() - tpsmillis > 1 * 60 * 1000 || tpsmillis == 0) {
    tpsmillis = millis();
    getTime();
    Serial.println(DateHeure);
  }
  if (millis() - sentMillis > 3 * 60 * 1000 || sentMillis == 0) {
    sentMillis = millis();
    Serial.println("Debut envoi *********************");
    envoiMail("Essai mail repete", "<p>This is the HTML message.</p>", true);  //Html
    //envoiMail("Essai mail repete", msgmail1(), true);
    //envoiMail("Essai mail repete", "<p>This is the texte message.</p>", false);  //Texte
    getTime();
    //envoiFichier("Envoi Journal ", "evene.csv");
    heapInfo.collect();
    heapInfo.print();
    Serial.print("**********************************date : ");
    Serial.println(DateHeure);
  }
}


void startserial() {

  Serial.begin(115200);

  int ii = 0;
  while (!Serial) {
    ++ii;
  }
  delay(8000);
  Serial.print("demarre serial : ");
  Serial.println(ii);
  Serial.print("Programme source : ");
  Serial.print(__FILE__);
  Serial.print(" ");
  Serial.print(__DATE__);
  Serial.print("-");
  Serial.println(__TIME__);
  Serial.println("\r\n");
}

void startLittleFS() {
  bool fsok = LittleFS.begin();
  Serial.printf_P(PSTR("LittleFS init: %s\n"), fsok ? PSTR("ok") : PSTR("fail!"));
  if (LittleFS.exists(ficheEve)) {
    Serial.print("Fichier Lecture ");
    Serial.println(ficheEve);

  } else {
    EnreEvenement("Creation Fichier evenement");
      Serial.print("Fichier Creation :");
    Serial.println(ficheEve);
  }
}

void startWifi() {
 Serial.print("++++++++++++++ +1 Start startwifisimple : ");
  WiFi.setHostname(nom);
  Serial.print(" nom: ");
  Serial.println(nom);
  WiFi.mode(WIFI_AP_STA);
  Serial.print(" nom: ");
  Serial.println(nom);
  WiFi.begin(ssid, password);
  Serial.print(" ssid: ");
  Serial.println(ssid);


  int i = 0;
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.print(++i);
    Serial.print(' ');
    if (i > 30) {
      WifiEtat = false;
      break;
    }
  }
  if (WifiEtat) {
    Serial.print(" ");
    Serial.print("WiFi connected..!");
    Serial.print("Got IP: ");
    Serial.print(WiFi.localIP());
  } else {
    Serial.print("WiFi Probleme............!");
    //WiFi.mode(WIFI_AP);
  }

  WiFi.setHostname(nom);
  Serial.println("Wifi Fin++++++++++++++++\r\n");
}

void startOTA() {  // Start the OTA service
  Serial.print("++++++++++++++ +2 Start Ota : ");
  ArduinoOTA.setHostname(nom);
  ArduinoOTA.onStart([]() {
    String type;
    if (ArduinoOTA.getCommand() == U_FLASH) {
      type = "sketch";
    } else {  // U_FS
      type = "filesystem";
    }

    // NOTE: if updating FS this would be the place to unmount FS using FS.end()
    Serial.println("Start updating " + type);
  });
  ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
  });
  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: % u % % \r", (progress / (total / 100)));
  });
  ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[ % u]: ", error);
    if (error == OTA_AUTH_ERROR) {
      Serial.println("Auth Failed");
    } else if (error == OTA_BEGIN_ERROR) {
      Serial.println("Begin Failed");
    } else if (error == OTA_CONNECT_ERROR) {
      Serial.println("Connect Failed");
    } else if (error == OTA_RECEIVE_ERROR) {
      Serial.println("Receive Failed");
    } else if (error == OTA_END_ERROR) {
      Serial.println("End Failed");
    }
  });
  ArduinoOTA.begin();
  Serial.println("OTA ready++++++++++++++++\r\n");
}

void startmail() {

  MailClient.networkReconnect(true);
  smtp.debug(1);

  smtp.callback(smtpCallback);

  config.server.host_name = SMTP_HOST;
  config.server.port = SMTP_PORT;
  config.login.email = AUTHOR_EMAIL;
  config.login.password = AUTHOR_PASSWORD;

  config.login.user_domain = F("127.0.0.1");

  config.time.ntp_server = F("pool.ntp.org,time.nist.gov");
  config.time.gmt_offset = 0;
  config.time.day_light_offset = 0;
  getTime();
}


void smtpCallback(SMTP_Status status) {

  Serial.println(status.info());

  if (status.success()) {

    Serial.println("----------------");
    MailClient.printf("Message sent success: %d\n", status.completedCount());
    MailClient.printf("Message sent failed: %d\n", status.failedCount());
    Serial.println("----------------\n");

    for (size_t i = 0; i < smtp.sendingResult.size(); i++) {
      SMTP_Result result = smtp.sendingResult.getItem(i);

      MailClient.printf("Message No: %d\n", i + 1);
      MailClient.printf("Status: %s\n", result.completed ? "success" : "failed");
      MailClient.printf("Date/Time: %s\n", MailClient.Time.getDateTimeString(result.timestamp, "%B %d, %Y %H:%M:%S").c_str());
      MailClient.printf("Recipient: %s\n", result.recipients.c_str());
      MailClient.printf("Subject: %s\n", result.subject.c_str());
    }
    Serial.println("----------------\n");

    smtp.sendingResult.clear();
  }
}

void EnreEvenement(String evene) {  //Enregistrement evenement dans journal
  getTime();
  File tempLog = LittleFS.open("/evene.csv", "a");  // Ecriture fichier Evenement.csv
  tempLog.print("debut;");
  tempLog.print(DateHeure);
  tempLog.print(";");
  tempLog.print(evene);
  tempLog.println(";fin");
  tempLog.close();
  Serial.print(":::::::::::::::::::::::::Journal : ");
  Serial.print(DateHeure);
  Serial.print(" + ");
  Serial.print(evene);
  Serial.println(" + ");
}

void getTime() {
  
  time(&maintenant);
  timeinfo = localtime(&maintenant);
  
  unsigned long epochtime = time(nullptr);
  if (epochtime < 1000000000 || epochtime > 2000000000) {
    Serial.print("Erreur heure");
    Serial.print(epochtime);
    Serial.print(" - ");
    epochtime = 0;
    Serial.println(epochtime);
  } else {
    int Min = timeinfo->tm_min;
    heureactu = timeinfo->tm_hour + 2;
    jouractu = timeinfo->tm_mday;
    int Mois = timeinfo->tm_mon + 1;
    int An = timeinfo->tm_year + 1900;
    sprintf(DateHeure, "%02d:%02d %02d/%02d/%d", heureactu, Min, jouractu, Mois, An);
  }
}


void envoiMail(String Sujet, String HtmlMsg, bool typehtml) {
  bool erreur = false;
  SMTP_Message message;

  message.sender.name = F("ESP Mail");
  message.sender.email = AUTHOR_EMAIL;
  // message.subject = F("Send Email with session reusage");
  message.subject = Sujet;
  message.addRecipient(nom, RECIPIENT_EMAIL);
  if (typehtml) message.html.content = HtmlMsg;
  else message.text.content = HtmlMsg;

  Serial.println();
  Serial.println("Sending Email...");

  if (!smtp.isLoggedIn()) {
    /* Set the TCP response read timeout in seconds */
    // smtp.setTCPTimeout(10);

    if (!smtp.connect(&config)) {
      MailClient.printf("Connection error, Status Code: %d, Error Code: %d, Reason: %s\n", smtp.statusCode(), smtp.errorCode(), smtp.errorReason().c_str());
      erreur = true;
    }

    if (!smtp.isLoggedIn()) {
      Serial.println("Error, Not yet logged in.");
      erreur = true;
    } else {
      if (smtp.isAuthenticated())
        Serial.println("Successfully logged in.");
      else
        Serial.println("Connected with no Auth.");
    }
  }

  if (!MailClient.sendMail(&smtp, &message, false) && !erreur)
    MailClient.printf("Error, Status Code: %d, Error Code: %d, Reason: %s\n", smtp.statusCode(), smtp.errorCode(), smtp.errorReason().c_str());
}

void envoiFichier(String Sujet, String Fichierx) {
  bool erreur = false;
  String Sujet1;
  String Journal1 = "=";

  SMTP_Message message;
  message.enable.chunking = true;
  message.sender.name = F("ESP Mail");
  message.sender.email = AUTHOR_EMAIL;
  Sujet1 = Sujet + nom;
  message.subject = Sujet1.c_str();
  message.addRecipient(nom, RECIPIENT_EMAIL);

  message.text.content = "Envoi Fichier";

  //envoi fichier
  SMTP_Attachment att;
  att.descr.filename = Fichierx;

  att.descr.mime = "text/plain";  //binary data
  att.file.path = Fichierx;
  att.file.storage_type = esp_mail_file_storage_type_flash;
  att.descr.transfer_encoding = Content_Transfer_Encoding::enc_base64;
  message.addAttachment(att);

  if (!smtp.isLoggedIn()) {
    /* Set the TCP response read timeout in seconds */
    // smtp.setTCPTimeout(10);
    Journal1 += Journal1 + "!isLoggedIn";
    if (!smtp.connect(&config)) {
      Journal1 += Journal1 + "!config";
      MailClient.printf("Connection error, Status Code: %d, Error Code: %d, Reason: %s\n", smtp.statusCode(), smtp.errorCode(), smtp.errorReason().c_str());
      erreur = true;
    }

    if (!smtp.isLoggedIn()) {
      Serial.println("Error, Not yet logged in.");
      Journal1 += Journal1 + "!isLoggedIn";
      erreur = true;
    } else {
      if (smtp.isAuthenticated())
        Serial.println("Successfully logged in.");
      else
        Serial.println("Connected with no Auth.");
    }
  }
  if (erreur) EnreEvenement(Journal1 + smtp.errorReason());
  if (!MailClient.sendMail(&smtp, &message, false) && !erreur)
    ESP_MAIL_PRINTF("Error, Status Code: %d, Error Code: %d, Reason: %s", smtp.statusCode(), smtp.errorCode(), smtp.errorReason().c_str());
}

//ini.h
const char* ssid = "xxx";
const char* password = "xxx";
//const char* nom = "Mail8266";
const char* poste = "Essai esp32";

#define ficheEve "evene.csv"
#define SMTP_HOST "smtp.laposte.net"
#define SMTP_PORT 465
#define AUTHOR_EMAIL "xxx@laposte.net"
#define AUTHOR_PASSWORD "Axxx1!"
#define RECIPIENT_EMAIL "xxx@laposte.net"
#define AUTHOR_NOM "Test"
```

**Additional information and things you've tried:**

**Comment by mobizt** [comment] 2023-10-18 07:12
If the internet is not the problem, you should test by sending email without attachment.

If you can send email without attachment, this means the issue is memory allocation failure in filesystems that leads to file reading timeout (always zero byte read returns from filesystem).

Filesystem memory allocation failure in Core library issue starts from ESP32 Core v2.0.1.

**Comment by mobizt** [comment] 2023-10-18 07:20
[This example](https://github.com/mobizt/ESP-Mail-Client/blob/master/examples/SMTP/Send_Reuse_Session/Send_Reuse_Session.ino) shows that you can send and resend email many times with single log in.

You can also log in every time when sending the email by closing the session after email sent.

**Comment by Michelbe30111** [comment] 2023-10-18 09:44
This example works very well with an esp8266 but with an esp32 only sends one email, the following ones are in error

**Comment by mobizt** [comment] 2023-10-18 10:20
It's your device or network problem.

I test with many ERP32 modules (WROOM, WROVER) with all networks (built-in WiFi, Ethernet and GSM modem) and all work fine.

**Closed** 2023-10-18 10:21 UTC
